#!/bin/bash
git add . #komanda "uzmanamo" mapju pievienosanai
git config --global user.name vasiks-kharms
git config --global user.email kdambeniece@gmail.com
git commit -m "Class_04a"
git push origin main

